// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Richard_SendRequest_FullMethodName = "/richard/SendRequest"
	Richard_SendReply_FullMethodName   = "/richard/SendReply"
)

// RichardClient is the client API for Richard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RichardClient interface {
	SendRequest(ctx context.Context, in *AskSend, opts ...grpc.CallOption) (*Empty, error)
	SendReply(ctx context.Context, in *Proceed, opts ...grpc.CallOption) (*Empty, error)
}

type richardClient struct {
	cc grpc.ClientConnInterface
}

func NewRichardClient(cc grpc.ClientConnInterface) RichardClient {
	return &richardClient{cc}
}

func (c *richardClient) SendRequest(ctx context.Context, in *AskSend, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Richard_SendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *richardClient) SendReply(ctx context.Context, in *Proceed, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Richard_SendReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RichardServer is the server API for Richard service.
// All implementations must embed UnimplementedRichardServer
// for forward compatibility.
type RichardServer interface {
	SendRequest(context.Context, *AskSend) (*Empty, error)
	SendReply(context.Context, *Proceed) (*Empty, error)
	mustEmbedUnimplementedRichardServer()
}

// UnimplementedRichardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRichardServer struct{}

func (UnimplementedRichardServer) SendRequest(context.Context, *AskSend) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedRichardServer) SendReply(context.Context, *Proceed) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReply not implemented")
}
func (UnimplementedRichardServer) mustEmbedUnimplementedRichardServer() {}
func (UnimplementedRichardServer) testEmbeddedByValue()                 {}

// UnsafeRichardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RichardServer will
// result in compilation errors.
type UnsafeRichardServer interface {
	mustEmbedUnimplementedRichardServer()
}

func RegisterRichardServer(s grpc.ServiceRegistrar, srv RichardServer) {
	// If the following call pancis, it indicates UnimplementedRichardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Richard_ServiceDesc, srv)
}

func _Richard_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RichardServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Richard_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RichardServer).SendRequest(ctx, req.(*AskSend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Richard_SendReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Proceed)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RichardServer).SendReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Richard_SendReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RichardServer).SendReply(ctx, req.(*Proceed))
	}
	return interceptor(ctx, in, info, handler)
}

// Richard_ServiceDesc is the grpc.ServiceDesc for Richard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Richard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "richard",
	HandlerType: (*RichardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequest",
			Handler:    _Richard_SendRequest_Handler,
		},
		{
			MethodName: "SendReply",
			Handler:    _Richard_SendReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
