// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AskSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeFormated  int64                  `protobuf:"varint,1,opt,name=timeFormated,proto3" json:"timeFormated,omitempty"`
	NodeId        int64                  `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskSend) Reset() {
	*x = AskSend{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskSend) ProtoMessage() {}

func (x *AskSend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskSend.ProtoReflect.Descriptor instead.
func (*AskSend) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *AskSend) GetTimeFormated() int64 {
	if x != nil {
		return x.TimeFormated
	}
	return 0
}

func (x *AskSend) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

type Proceed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProceedBool   bool                   `protobuf:"varint,1,opt,name=proceedBool,proto3" json:"proceedBool,omitempty"`
	NodeId        int64                  `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	TimeFormated  int64                  `protobuf:"varint,3,opt,name=timeFormated,proto3" json:"timeFormated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proceed) Reset() {
	*x = Proceed{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proceed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proceed) ProtoMessage() {}

func (x *Proceed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proceed.ProtoReflect.Descriptor instead.
func (*Proceed) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Proceed) GetProceedBool() bool {
	if x != nil {
		return x.ProceedBool
	}
	return false
}

func (x *Proceed) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Proceed) GetTimeFormated() int64 {
	if x != nil {
		return x.TimeFormated
	}
	return 0
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"F\n" +
	"\bask_send\x12\"\n" +
	"\ftimeFormated\x18\x01 \x01(\x03R\ftimeFormated\x12\x16\n" +
	"\x06NodeId\x18\x02 \x01(\x03R\x06NodeId\"\a\n" +
	"\x05Empty\"g\n" +
	"\aproceed\x12 \n" +
	"\vproceedBool\x18\x01 \x01(\bR\vproceedBool\x12\x16\n" +
	"\x06NodeId\x18\x02 \x01(\x03R\x06NodeId\x12\"\n" +
	"\ftimeFormated\x18\x03 \x01(\x03R\ftimeFormated2P\n" +
	"\arichard\x12$\n" +
	"\vSendRequest\x12\t.ask_send\x1a\b.proceed\"\x00\x12\x1f\n" +
	"\tSendReply\x12\b.proceed\x1a\x06.Empty\"\x00B\x14Z\x12Richard/GRPC/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_proto_goTypes = []any{
	(*AskSend)(nil), // 0: ask_send
	(*Empty)(nil),   // 1: Empty
	(*Proceed)(nil), // 2: proceed
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: richard.SendRequest:input_type -> ask_send
	2, // 1: richard.SendReply:input_type -> proceed
	2, // 2: richard.SendRequest:output_type -> proceed
	1, // 3: richard.SendReply:output_type -> Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
